namespace Whycespace.Domain.BusinessSystem.Marketplace.ParticipantMarket;

public sealed record ParticipantMarketRegisteredEvent(ParticipantMarketId ParticipantMarketId, ParticipantReference Reference);
