namespace Whycespace.Domain.BusinessSystem.Provider.ProviderGovernance.ProviderAgreement;

public sealed record ProviderAgreementSuspendedEvent(ProviderAgreementId ProviderAgreementId, DateTimeOffset SuspendedAt);
