using Whycespace.Domain.SharedKernel;
using Whycespace.Shared.Primitives.Id;

namespace Whycespace.Domain.DecisionSystem.Governance.Guardian;

/// <summary>
/// Aggregate root representing a governance recommendation generated by AGA.
/// Advisory-only — cannot activate, approve, or modify policy state directly.
/// </summary>
public sealed class GovernanceRecommendationAggregate : AggregateRoot
{
    public RecommendationId RecommendationId { get; private set; } = null!;
    public RecommendationSource Source { get; private set; }
    public IReadOnlyList<Guid> AffectedPolicies { get; private set; } = [];
    public IReadOnlyList<string> SuggestedChanges { get; private set; } = [];
    public RecommendationConfidence Confidence { get; private set; } = null!;
    public ImpactEstimate Impact { get; private set; } = null!;
    public RiskEstimate Risk { get; private set; } = null!;
    public DateTimeOffset CreatedAt { get; private set; }
    public RecommendationStatus Status { get; private set; }

    private readonly List<RecommendationInsight> _insights = [];
    public IReadOnlyList<RecommendationInsight> Insights => _insights.AsReadOnly();

    private GovernanceRecommendationAggregate() { }

    public static GovernanceRecommendationAggregate Create(
        RecommendationSource source,
        IReadOnlyList<Guid> affectedPolicies,
        IReadOnlyList<string> suggestedChanges,
        RecommendationConfidence confidence,
        ImpactEstimate impact,
        RiskEstimate risk,
        IReadOnlyList<RecommendationInsight> insights,
        DateTimeOffset timestamp)
    {
        var recommendation = new GovernanceRecommendationAggregate();
        var id = RecommendationId.FromSeed($"GovernanceRecommendation:{source}:{confidence.Value}:{affectedPolicies.Count}");

        recommendation.Id = id.Value;
        recommendation.RecommendationId = id;
        recommendation.Source = source;
        recommendation.AffectedPolicies = affectedPolicies;
        recommendation.SuggestedChanges = suggestedChanges;
        recommendation.Confidence = confidence;
        recommendation.Impact = impact;
        recommendation.Risk = risk;
        recommendation.CreatedAt = timestamp;
        recommendation.Status = RecommendationStatus.Draft;
        recommendation._insights.AddRange(insights);

        recommendation.EnsureInvariant(
            affectedPolicies.Count > 0,
            InvalidRecommendationError.EmptyPolicies,
            "A recommendation must affect at least one policy.");

        recommendation.EnsureInvariant(
            insights.Count > 0,
            InvalidRecommendationError.MissingInsights,
            "A recommendation must include at least one supporting insight.");

        recommendation.RaiseDomainEvent(new RecommendationGeneratedEvent(
            id.Value,
            source.ToString(),
            affectedPolicies.Count,
            confidence.Value));

        return recommendation;
    }

    public void MarkReviewed(string? reviewNotes = null)
    {
        EnsureValidTransition(Status, RecommendationStatus.Reviewed, IsValidTransition);
        Status = RecommendationStatus.Reviewed;
        RaiseDomainEvent(new RecommendationReviewedEvent(RecommendationId.Value, Status.ToString(), reviewNotes));
    }

    public void Approve(string? reviewNotes = null)
    {
        EnsureValidTransition(Status, RecommendationStatus.Approved, IsValidTransition);
        Status = RecommendationStatus.Approved;
        RaiseDomainEvent(new RecommendationReviewedEvent(RecommendationId.Value, Status.ToString(), reviewNotes));
    }

    public void Reject(string? reviewNotes = null)
    {
        EnsureValidTransition(Status, RecommendationStatus.Rejected, IsValidTransition);
        Status = RecommendationStatus.Rejected;
        RaiseDomainEvent(new RecommendationReviewedEvent(RecommendationId.Value, Status.ToString(), reviewNotes));
    }

    private static bool IsValidTransition(RecommendationStatus from, RecommendationStatus to) =>
        (from, to) switch
        {
            (RecommendationStatus.Draft, RecommendationStatus.Reviewed) => true,
            (RecommendationStatus.Reviewed, RecommendationStatus.Approved) => true,
            (RecommendationStatus.Reviewed, RecommendationStatus.Rejected) => true,
            _ => false
        };
}
