namespace Whycespace.Domain.BusinessSystem.Provider.ProviderCore.ProviderCapability;

public sealed record ProviderCapabilityUpdatedEvent(ProviderCapabilityId ProviderCapabilityId, CapabilityName Name);
