namespace Whycespace.Domain.BusinessSystem.Order.OrderChange.FulfillmentInstruction;

public sealed record FulfillmentInstructionIssuedEvent(FulfillmentInstructionId FulfillmentInstructionId, DateTimeOffset IssuedAt);
